In [1]:
import numpy as np
import nashpy as ns

In [2]:
grid = np.array([[4,6,5,10,6], 
        [7,8,5,9,10], 
        [8,9,11,10,9],
                [6,4,10,6,4]])

In [3]:
rps = ns.Game(grid)

In [4]:
rps

Zero sum game with payoff matrices:

Row player:
[[ 4  6  5 10  6]
 [ 7  8  5  9 10]
 [ 8  9 11 10  9]
 [ 6  4 10  6  4]]

Column player:
[[ -4  -6  -5 -10  -6]
 [ -7  -8  -5  -9 -10]
 [ -8  -9 -11 -10  -9]
 [ -6  -4 -10  -6  -4]]

In [5]:
eqs = rps.support_enumeration()
list(eqs)

[(array([0., 0., 1., 0.]), array([ 1.,  0.,  0., -0.,  0.]))]

## Decide whether a firm should advertise or not

In [6]:
print("         adv       no-adv")
print("adv.     100,85   90,80")
print("no-adv.  75,60    60,70")

         adv       no-adv
adv.     100,85   90,80
no-adv.  75,60    60,70


In [7]:
A = np.array([[100,75],[90,60]]) # A is the row player
B = np.array([[85,60],[80,70]]) # B is the column player

In [8]:
game = ns.Game(A,B)

In [9]:
game

Bi matrix game with payoff matrices:

Row player:
[[100  75]
 [ 90  60]]

Column player:
[[85 60]
 [80 70]]

In [10]:
eqs = game.support_enumeration()
list(eqs)

[(array([1., 0.]), array([1., 0.]))]

In [11]:
print("Dominant strategy : There is one optimal strategy for each player irrespective of what strategy the other player     adopts.") 

Dominant strategy : There is one optimal strategy for each player irrespective of what strategy the other player     adopts.


In [12]:
print("Whatever choice B makes, A should always choose to advertise.")

Whatever choice B makes, A should always choose to advertise.


In [13]:
print("B unfortunately, does not have a dominant strategy.")
print("B's choice will depend on A's choice")
print("If A chooses to advertise, B's best choice will be to advertise as well")
print("If A chooses to not-advertise, B's best choice would be to not advertise")

B unfortunately, does not have a dominant strategy.
B's choice will depend on A's choice
If A chooses to advertise, B's best choice will be to advertise as well
If A chooses to not-advertise, B's best choice would be to not advertise


In [14]:
print("A's strategy however, should always be to advertise irrespective of B's decision")

A's strategy however, should always be to advertise irrespective of B's decision


In [15]:
grid = np.array([[25, 20, 35], 
        [50, 45, 55], 
        [58, 40, 42]])

In [16]:
rps = ns.Game(grid)

In [17]:
rps

Zero sum game with payoff matrices:

Row player:
[[25 20 35]
 [50 45 55]
 [58 40 42]]

Column player:
[[-25 -20 -35]
 [-50 -45 -55]
 [-58 -40 -42]]

In [18]:
eqs = rps.support_enumeration()

In [19]:
list(eqs)

[(array([0., 1., 0.]), array([0., 1., 0.]))]

In [20]:
print("Both players should go for the 2nd strategy")

Both players should go for the 2nd strategy


In [21]:
grid = np.array([[9, 7], 
        [5, 11]
                ])

In [22]:
rps = ns.Game(grid)

In [23]:
rps

Zero sum game with payoff matrices:

Row player:
[[ 9  7]
 [ 5 11]]

Column player:
[[ -9  -7]
 [ -5 -11]]

In [24]:
eqs = rps.support_enumeration()

In [25]:
list(eqs)

[(array([0.75, 0.25]), array([0.5, 0.5]))]

## Rock Paper Scissor Game

In [26]:
A = np.array([[0, -1, 1], [1, 0, -1], [-1, 1, 0]])
rps = ns.Game(A)
rps

Zero sum game with payoff matrices:

Row player:
[[ 0 -1  1]
 [ 1  0 -1]
 [-1  1  0]]

Column player:
[[ 0  1 -1]
 [-1  0  1]
 [ 1 -1  0]]

In [27]:
#Zero sum game with payoff matrices --> row player = -column player

In [28]:
eqs = rps.support_enumeration()

In [29]:
list(eqs)

[(array([0.33333333, 0.33333333, 0.33333333]),
  array([0.33333333, 0.33333333, 0.33333333]))]

In [30]:
sigma_r =  np.array([1,0,0])  # --> row player always takes rock
sigma_c =  np.array([0,0,1])  # --> column player always takes scissor

In [31]:
rps = ns.Game(A)

In [32]:
rps[sigma_r,sigma_c] 

array([ 1, -1])

In [33]:
print("if the row player always takes rock, and the column player always takes scissor, the row player will win 100% of the time")

if the row player always takes rock, and the column player always takes scissor, the row player will win 100% of the time


In [34]:
sigma_r =  np.array([0.8,0.1,0.1]) #--> takes rock 80% of the time and papers and scissors 10% of the time each
sigma_c =  np.array([0,0,1]) #--> takes scissors 100% of the time

In [35]:
rps = ns.Game(A)
rps[sigma_r,sigma_c] 

array([ 0.7, -0.7])

In [36]:
print("A pair of strategies is said to be Nash equilibrium (NE), if optimal choice of Player A given Player B’s choice coincides with optimal choice of Player B given Player A’s choice. In simple terms, initially neither player knows what the other player will do when deciding or making a choice. Hence NE is a pair of choices/strategies/expectations where neither player wants to change their behaviour even after the strategy/choice of the other player is revealed.")

A pair of strategies is said to be Nash equilibrium (NE), if optimal choice of Player A given Player B’s choice coincides with optimal choice of Player B given Player A’s choice. In simple terms, initially neither player knows what the other player will do when deciding or making a choice. Hence NE is a pair of choices/strategies/expectations where neither player wants to change their behaviour even after the strategy/choice of the other player is revealed.


In [37]:
print("There can be multiple Nash Equilibrium")

There can be multiple Nash Equilibrium
